name: Test Matrix

on:
  workflow_dispatch:

jobs:
  trigger-test-matrix:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tenant: [mt, ce, ws]
        aws_region: [us-west-2]
        env: [sandbox1]
        include: # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
          - tenant: mt
            aws_region: us-west-2
            env: sandbox2
          - tenant: mt
            aws_region: eu-central-1
            env: sandbox1
          - tenant: bn
            aws_region: ap-northeast-1
            env: sandbox1 
    steps:
        - name: Dump payload
          run: |
            echo ${{ matrix.tenant }}-${{ matrix.aws_region }}-${{ matrix.env }}
      