name: Test Datetime

on:
  workflow_dispatch:

jobs:
  test-datetime:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Current Datetime in UTC
        run: |
            current_datetime_plus_five_mins=$(gdate -d '+5 mins' -u)
            echo $current_datetime_plus_five_mins
            echo "::set-output name=date::$current_datetime_plus_five_mins
      