name: Test Datetime

on:
  workflow_dispatch:

jobs:
  test-datetime:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Current Datetime in UTC
        run: |
            current_datetime_plus_five_mins=$(date -d '+5 minutes' -u +"%d-%m-%Y %H:%M:%S")
            current_datetime_plus_one_hour=$(date -d '+1 hour' -u +"%d-%m-%Y %H:%M:%S")
            echo $current_datetime_plus_five_mins
            echo $current_datetime_plus_one_hour
            echo "::set-output name=datetime_plus_five_min::$current_datetime_plus_five_mins"
            echo "::set-output name=datetime_plus_one_hour::$current_datetime_plus_one_hour"
      