name: Test Datetime

on:
  workflow_dispatch:

jobs:
  test-datetime:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Current Datetime in UTC
        run: |
            current_datetime=$(date +%d/%m/%Y %H:%M:%S)
            echo $current_datetime
            echo "::set-output name=date::$(date -d "($current_datetime) +5mins" '+%Y-%m-%d %H:%M:%S')"
      